
include ..\config.nmake

all: ..\lib\io_proc.lib

io_proc.lib:  io_proc.obj  cls.obj
	$(LIBRARIER) /OUT:io_proc.lib io_proc.obj  cls.obj

..\lib\io_proc.lib: io_proc.lib
	mkdir ..\lib
	copy io_proc.lib  ..\lib\io_proc.lib


io_proc.obj: io_proc.asm
	$(ASM) $(ASM_FLAGS) /I ..\include\windows io_proc.asm

cls.obj: cls.c
	$(CC) $(CFLAGS) /c cls.c

clean:
	del io_proc.obj
	del cls.obj
	del io_proc.lib